Improve error logic

diff --git a/check-capabilities/action.yml b/check-capabilities/action.yml
--- a/check-capabilities/action.yml
+++ b/check-capabilities/action.yml
@@ -26,16 +26,16 @@ runs:
         source $MOOSE_UTILS_PATH
 
         echo "::group::Show capabilities"
-        print_and_run "${{ inputs.executable }}" --show-capabilities
+        if ! print_and_run "${{ inputs.executable }}" --show-capabilities; then
+          echo "::error::Failed to show application capabilities"
+          exit 1
+        fi
         echo "::endgroup::"
 
         echo "::group::Check capabilities"
-
         readarray -t capabilities <<< "${{ inputs.capabilities }}"
-
         check_summary=()
         check_failed=
-
         for capability in "${capabilities[@]}"; do
           command=("${{ inputs.capabilities }}" "--check-capabilities='$capability'")
           return_code=0
@@ -54,14 +54,17 @@ runs:
           fi
           check_summary+=("$result_str $capability")
         done
-
+        echo "::endgroup::"
 
         echo "::group::Check capabilities result"
         for result in "${check_summary[@]}"; do
           echo "$result"
         done
+        if [ -n "$check_failed" ]; then
+        fi
         echo "::endgroup::"
 
         if [ -n "$check_failed" ]; then
+          echo "::error::Capabilities check failed"
           exit 1
         fi
