Applied shfmt

diff --git a/unit/run_tests b/unit/run_tests
--- a/unit/run_tests
+++ b/unit/run_tests
@@ -3,16 +3,14 @@
 APPLICATION_NAME=platypus
 # If $METHOD is not set, use opt
 if [ -z $METHOD ]; then
-  export METHOD=opt
+    export METHOD=opt
 fi
 
-if [ -e ./unit/$APPLICATION_NAME-unit-$METHOD ]
-then
-  ./unit/$APPLICATION_NAME-unit-$METHOD
-elif [ -e ./$APPLICATION_NAME-unit-$METHOD ]
-then
-  ./$APPLICATION_NAME-unit-$METHOD
+if [ -e ./unit/$APPLICATION_NAME-unit-$METHOD ]; then
+    ./unit/$APPLICATION_NAME-unit-$METHOD
+elif [ -e ./$APPLICATION_NAME-unit-$METHOD ]; then
+    ./$APPLICATION_NAME-unit-$METHOD
 else
-  echo "Executable missing!"
-  exit 1
+    echo "Executable missing!"
+    exit 1
 fi
