Initial working commit
To use/test on Sawtooth:

```bash
module load use.moose
module load moosetainer
```

Create a source file which will function to load the above modules
when QSUB launches on nodes:

```pre
$ cat my_apptainer_env.sh
source /etc/profile
export MOOSE_COMMAND=${MOOSE_COMMAND:-"null"}
module load use.moose openmpi
module load moosetainer
```

Then be sure to tell TestHarness to source this file while using pbs
options:

```bash
./run_tests --pbs alltests --pbs-pre-source /abs/path/to/my_apptainer_env.sh
```

Closes #25038

diff --git a/python/TestHarness/schedulers/pbs_template b/python/TestHarness/schedulers/pbs_template
--- a/python/TestHarness/schedulers/pbs_template
+++ b/python/TestHarness/schedulers/pbs_template
@@ -7,10 +7,33 @@
 #PBS -j oe
 #PBS -o <OUTPUT>
 #PBS -l place=free
-<PRE_COMMAND>
 JOB_NUM=${PBS_JOBID%\.*}
-
 export MV2_ENABLE_AFFINITY=0
 
-cd <WORKING_DIR>
-<COMMAND>
+export MOOSE_COMMAND="cd <WORKING_DIR>; <COMMAND>"
+
+# --pbs-pre-source:
+<PRE_COMMAND>
+
+if [ -n "<USE_APPTAINER>" ]; then
+    if [ -z "${APPTAINER_URI}" ]; then
+      printf "Unknown Apptainer whereabouts. Cannot continue.
+Please use --pbs-pre-source to source some file that will establish
+necessary Apptainer variables.
+
+Missing APPTAINER_URI, where APPTAINER_URI satisfies the following
+funtionality:
+
+    apptainer exec \${APPTAINER_URI}\n\n"
+      exit 1
+    fi
+    if [ -z "${APPTAINER_BINDPATH}" ]; then
+        printf "Warning: No APPTAINER_BINDPATH detected. Perhaps you do not need them?\n"
+    fi
+    # TestHarness influential Apptainer environment variables
+    export APPTAINERENV_MOOSE_STAGE='loopback'
+    export APPTAINERENV_PBS_NODEFILE=${PBS_NODEFILE}
+    export APPTAINERENV_APPTAINER_URI=${APPTAINER_URI}
+    export MOOSE_COMMAND="apptainer exec --containall ${APPTAINER_URI} \"${MOOSE_COMMAND}\""
+fi
+eval ${MOOSE_COMMAND}
