Syntax changes
Reword a few things for easier understanding

diff --git a/python/TestHarness/schedulers/pbs_template b/python/TestHarness/schedulers/pbs_template
--- a/python/TestHarness/schedulers/pbs_template
+++ b/python/TestHarness/schedulers/pbs_template
@@ -17,7 +17,7 @@ export MOOSE_COMMAND="cd <WORKING_DIR>; <COMMAND>"
 
 if [ -n "<USE_APPTAINER>" ]; then
     if [ -z "${APPTAINER_URI}" ]; then
-      printf "Unknown Apptainer whereabouts. Cannot continue.
+        printf "Unknown Apptainer whereabouts. Cannot continue.
 Please use --pbs-pre-source to source some file that will establish
 necessary Apptainer variables.
 
@@ -25,13 +25,13 @@ Missing APPTAINER_URI, where APPTAINER_URI satisfies the following
 funtionality:
 
     apptainer exec \${APPTAINER_URI}\n\n"
-      exit 1
+        exit 1
     fi
     if [ -z "${APPTAINER_BINDPATH}" ]; then
         printf "Warning: No APPTAINER_BINDPATH detected. Perhaps you do not need them?\n"
     fi
     # TestHarness influential Apptainer environment variables
-    export APPTAINERENV_MOOSE_STAGE='loopback'
+    export APPTAINERENV_MOOSE_STAGE='2'
     export APPTAINERENV_PBS_NODEFILE=${PBS_NODEFILE}
     export APPTAINERENV_APPTAINER_URI=${APPTAINER_URI}
     export MOOSE_COMMAND="apptainer exec --containall ${APPTAINER_URI} \"${MOOSE_COMMAND}\""
